/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab23;

import javax.swing.JTextField;

/**
 *
 * @author Gurkan
 */
public class Gui extends javax.swing.JFrame {
    private String gKAsdi;
    //kayit ol degiskenleri
    private String kKullaniciAdi = new String();
    private String kSsifre = new String();
    private boolean kOdendi = true;
    private boolean kAdmin;
    private boolean kPremium;
    //giris yap degiskenleri
    public String gKullaniciAdi = new String();

    public String getgKullaniciAdi() {
        return gKullaniciAdi;
    }
    private String gSsifre;

    public JTextField getgKadi() {
        return gKadi;
    }
    private String agKullaniciAdi = new String();
    private String agSsifre;
    private boolean gAdmin;
    //mysql
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }
    public Gui(int a){  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kAdiBos2 = new javax.swing.JLabel();
        sifreBos2 = new javax.swing.JLabel();
        adminGiris = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gKadi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adminGirisButon = new javax.swing.JButton();
        kAdiBos3 = new javax.swing.JLabel();
        sifreBos3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gSifre = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kKAdi = new javax.swing.JTextField();
        kayitButon = new javax.swing.JButton();
        adminMi = new javax.swing.JCheckBox();
        premiumMu = new javax.swing.JCheckBox();
        kayitBasarili = new javax.swing.JLabel();
        kAdiBos = new javax.swing.JLabel();
        sifreBos = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        kSifre = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        giris = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gKadi1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        girisButon1 = new javax.swing.JButton();
        kAdiBos1 = new javax.swing.JLabel();
        sifreBos1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gSifre1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        kAdiBos2.setForeground(new java.awt.Color(255, 0, 102));
        kAdiBos2.setText("Kullanici Adi Bos Olamaz");
        kAdiBos.setVisible(false);

        sifreBos2.setForeground(new java.awt.Color(255, 0, 102));
        sifreBos2.setText("Sifre Bos Olamaz");
        sifreBos.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminGiris.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Giriş Yap", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(102, 255, 51))); // NOI18N
        adminGiris.setForeground(new java.awt.Color(0, 0, 255));
        adminGiris.setToolTipText("");
        adminGiris.setName(""); // NOI18N

        jLabel1.setText("Kullanıcı Adı:");

        gKadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gKadiKeyReleased(evt);
            }
        });

        jLabel2.setText("Şifre:");

        adminGirisButon.setText("Admin Girişi Yap");
        adminGirisButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisButonActionPerformed(evt);
            }
        });

        kAdiBos3.setForeground(new java.awt.Color(255, 0, 0));
        kAdiBos3.setText("Kullanici Adi Bos Olamaz");
        kAdiBos3.setVisible(false);

        sifreBos3.setForeground(new java.awt.Color(255, 0, 0));
        sifreBos3.setText("Sifre Bos Olamaz");
        sifreBos3.setVisible(false);

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Kullanici adi veya sifre yanlis");
        jLabel9.setVisible(false);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Lütfen Kullanıcı Girişini Kullanın");
        jLabel10.setVisible(false);

        gSifre.setText("jPasswordField1");
        gSifre.setText("");
        gSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gSifreKeyReleased(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("Admin Girişi Yap");

        javax.swing.GroupLayout adminGirisLayout = new javax.swing.GroupLayout(adminGiris);
        adminGiris.setLayout(adminGirisLayout);
        adminGirisLayout.setHorizontalGroup(
            adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminGirisLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminGirisButon))
            .addGroup(adminGirisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminGirisLayout.createSequentialGroup()
                        .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminGirisLayout.createSequentialGroup()
                                .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gKadi)
                                    .addComponent(gSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kAdiBos3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreBos3)))
                    .addGroup(adminGirisLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminGirisLayout.setVerticalGroup(
            adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminGirisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminGirisLayout.createSequentialGroup()
                        .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(gKadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sifreBos3))))
                    .addComponent(kAdiBos3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminGirisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adminGirisButon))
                    .addGroup(adminGirisLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Kayıt Ol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel3.setText("Kullanıcı Adı:");

        jLabel4.setText("Şifre:");

        kKAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kKAdiKeyReleased(evt);
            }
        });

        kayitButon.setText("Kayıt Ol");
        kayitButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitButonActionPerformed(evt);
            }
        });

        adminMi.setText("Admin?");
        adminMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMiActionPerformed(evt);
            }
        });

        premiumMu.setText("Premium Kullanıcı?");

        kayitBasarili.setBackground(new java.awt.Color(51, 255, 51));
        kayitBasarili.setForeground(new java.awt.Color(102, 255, 0));
        kayitBasarili.setText("Kayit Basarili");
        kayitBasarili.setVisible(false);

        kAdiBos.setForeground(new java.awt.Color(255, 0, 0));
        kAdiBos.setText("Kullanici Adi Bos Olamaz");
        kAdiBos.setVisible(false);

        sifreBos.setForeground(new java.awt.Color(255, 0, 0));
        sifreBos.setText("Sifre Bos Olamaz");
        sifreBos.setVisible(false);

        max.setForeground(new java.awt.Color(255, 0, 0));
        max.setText("Min 5 Maxiumum 30 karakter");
        max.setVisible(false);

        kSifre.setText("jPasswordField1");
        kSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kSifreActionPerformed(evt);
            }
        });
        kSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kSifreKeyReleased(evt);
            }
        });
        kSifre.setText("");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Kullanici Adi Alinmis");
        jLabel12.setVisible(false);

        jLabel13.setText("Mail:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kKAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(kSifre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifreBos)
                    .addComponent(kAdiBos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(premiumMu))
                            .addComponent(max))
                        .addGap(69, 69, 69)
                        .addComponent(adminMi)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kayitBasarili, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kayitButon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(72, 72, 72))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kKAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kAdiBos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sifreBos)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(max)
                    .addComponent(kayitBasarili))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premiumMu)
                    .addComponent(adminMi)
                    .addComponent(kayitButon))
                .addContainerGap())
        );

        giris.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Giriş Yap", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(102, 255, 51))); // NOI18N
        giris.setForeground(new java.awt.Color(0, 255, 0));

        jLabel5.setText("Kullanıcı Adı:");

        gKadi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gKadi1KeyReleased(evt);
            }
        });

        jLabel6.setText("Şifre:");

        girisButon1.setText("Giriş Yap");
        girisButon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButon1ActionPerformed(evt);
            }
        });

        kAdiBos1.setForeground(new java.awt.Color(255, 0, 0));
        kAdiBos1.setText("Kullanici Adi Bos Olamaz");
        kAdiBos1.setVisible(false);

        sifreBos1.setForeground(new java.awt.Color(255, 0, 0));
        sifreBos1.setText("Sifre Bos Olamaz");
        sifreBos1.setVisible(false);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Kullanici adi veya sifre yanlis");
        jLabel8.setVisible(false);

        gSifre1.setText("jPasswordField1");
        gSifre1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gSifre1.setText("");
        gSifre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gSifre1KeyReleased(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Lütfen Admin Girişini Kullanın");
        jLabel11.setVisible(false);

        javax.swing.GroupLayout girisLayout = new javax.swing.GroupLayout(giris);
        giris.setLayout(girisLayout);
        girisLayout.setHorizontalGroup(
            girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, girisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(girisButon1)
                .addContainerGap())
            .addGroup(girisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(girisLayout.createSequentialGroup()
                        .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(girisLayout.createSequentialGroup()
                                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gKadi1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(gSifre1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kAdiBos1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreBos1)))
                    .addGroup(girisLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        girisLayout.setVerticalGroup(
            girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisLayout.createSequentialGroup()
                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(girisLayout.createSequentialGroup()
                        .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gKadi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kAdiBos1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(gSifre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sifreBos1))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(girisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(girisButon1)
                    .addComponent(jLabel11)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminGiris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(adminGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(giris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        adminGiris.getAccessibleContext().setAccessibleName("Admin Girişi Yap");
        giris.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void kayitHataMesajlariniKapat() {
        kAdiBos.setVisible(false);
        sifreBos.setVisible(false);
        kayitBasarili.setVisible(false);
        max.setVisible(false);
        kAdiBos1.setVisible(false);
        sifreBos1.setVisible(false);
        kAdiBos3.setVisible(false);
        sifreBos3.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
    }
    private void adminGirisButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisButonActionPerformed
        kayitHataMesajlariniKapat();
        if(agKullaniciAdi.isBlank()){
           kAdiBos3.setVisible(true);
           if(agSsifre.isBlank()) {
            sifreBos3.setVisible(true);
        }
        }
        else if(agSsifre.isBlank()) {
            sifreBos3.setVisible(true);
        }   
        else {
        Mysql mysql = new Mysql(true,agKullaniciAdi,agSsifre);
            if(mysql.getAkayitVarMi()==0)
                jLabel9.setVisible(true);
            else if(mysql.getAkayitVarMi()==1)
                jLabel10.setVisible(true);
            else{
                this.dispose();
                aPencere pencere = new aPencere();
                pencere.setVisible(true);
            }
        }
        gSifre1.setText(""); 
    }//GEN-LAST:event_adminGirisButonActionPerformed

    private void kayitButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitButonActionPerformed
        kayitHataMesajlariniKapat();
        Mysql mysql2 = new Mysql(kKullaniciAdi);
        if(kKullaniciAdi.isBlank()){
           kAdiBos.setVisible(true);
            if(kSsifre.isBlank()) {
            sifreBos.setVisible(true);
        }
        }
        else if(kSsifre.isBlank()) {
            sifreBos.setVisible(true);
        }
        else if(kKullaniciAdi.length()>30 || kSsifre.length()>30 || kKullaniciAdi.length()<5 || kSsifre.length()<5) {
            max.setVisible(true);
        }
        else if(mysql2.isAlinmis())
        jLabel12.setVisible(true);
        else {
        kayitBasarili.setVisible(true);
        Mysql mysql = new Mysql(kKullaniciAdi,kSsifre,adminMi.isSelected(),premiumMu.isSelected(),jTextField1.getText());
        }
        kKAdi.setText("");
        kSifre.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_kayitButonActionPerformed

    private void kKAdiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kKAdiKeyReleased
        kKullaniciAdi = new String(kKAdi.getText());
    }//GEN-LAST:event_kKAdiKeyReleased
    //giris butonu
    private void girisButon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButon1ActionPerformed
        kayitHataMesajlariniKapat();
        if(gKullaniciAdi.isBlank()){
           kAdiBos1.setVisible(true);
           if(gSsifre.isBlank()) {
            sifreBos1.setVisible(true);
        }
        }
        else if(gSsifre.isBlank()) {
            sifreBos1.setVisible(true);
        }   
        else {
        Mysql mysql = new Mysql(gKullaniciAdi,gSsifre);
            if(mysql.getKayitVarMi()==0)
                jLabel11.setVisible(true);
            else if(mysql.getKayitVarMi()==1)
                jLabel8.setVisible(true);
            else{
                this.dispose();
                KPencere pencere = new KPencere(gKullaniciAdi);
                pencere.setVisible(true);
            }
        }
        gSifre1.setText(""); 
    }//GEN-LAST:event_girisButon1ActionPerformed

    private void kSifreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kSifreKeyReleased
        kSsifre = new String(kSifre.getPassword());
    }//GEN-LAST:event_kSifreKeyReleased

    private void gKadi1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKadi1KeyReleased
        gKullaniciAdi=gKadi1.getText();
    }//GEN-LAST:event_gKadi1KeyReleased

    private void gSifre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gSifre1KeyReleased
        gSsifre = new String(gSifre1.getPassword());
    }//GEN-LAST:event_gSifre1KeyReleased

    private void gKadiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKadiKeyReleased
        agKullaniciAdi=gKadi.getText();
    }//GEN-LAST:event_gKadiKeyReleased

    private void gSifreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gSifreKeyReleased
        agSsifre = new String(gSifre.getPassword());
    }//GEN-LAST:event_gSifreKeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void kSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kSifreActionPerformed

    private void adminMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMiActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminGiris;
    private javax.swing.JButton adminGirisButon;
    private javax.swing.JCheckBox adminMi;
    private javax.swing.JTextField gKadi;
    private javax.swing.JTextField gKadi1;
    private javax.swing.JPasswordField gSifre;
    private javax.swing.JPasswordField gSifre1;
    private javax.swing.JPanel giris;
    private javax.swing.JButton girisButon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kAdiBos;
    private javax.swing.JLabel kAdiBos1;
    private javax.swing.JLabel kAdiBos2;
    private javax.swing.JLabel kAdiBos3;
    private javax.swing.JTextField kKAdi;
    private javax.swing.JPasswordField kSifre;
    private javax.swing.JLabel kayitBasarili;
    private javax.swing.JButton kayitButon;
    private javax.swing.JLabel max;
    private javax.swing.JCheckBox premiumMu;
    private javax.swing.JLabel sifreBos;
    private javax.swing.JLabel sifreBos1;
    private javax.swing.JLabel sifreBos2;
    private javax.swing.JLabel sifreBos3;
    // End of variables declaration//GEN-END:variables
}
