/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab23;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Gurkan
 */
public class KPencere extends javax.swing.JFrame {

    private Connection con;
    private String kullaniciAdi = new String();
    private String yeniDeger = new String();
    private String arananKullaniciAdi = new String();
    /**
     * Creates new form KPencere
     * @param gKullaniciAdi
     */
    public KPencere(String gKullaniciAdi) {
        kullaniciAdi = gKullaniciAdi;
        initComponents();
        try {
            Connection();
            String query = "Select premium From kullanicilar WHERE kullaniciAdi= '" + kullaniciAdi + "'";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            rs.next();
            if(rs.getInt("premium")==1){
                jButton23.setVisible(true);
                jButton24.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        kullaniciAdiLabel.setText(kullaniciAdi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        aramaKutusu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        popButon = new javax.swing.JButton();
        jazzButon = new javax.swing.JButton();
        klasikButon = new javax.swing.JButton();
        aramaKutucuk = new javax.swing.JLabel();
        kullaniciAdiLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jButton16.setText("Tümünü Ekle");

        jButton18.setText("Tümünü Ekle");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aramaKutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaKutusuActionPerformed(evt);
            }
        });

        jButton1.setText("Takip Edilenleri Goruntule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        popButon.setText("Pop Sarkilar");
        popButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popButonActionPerformed(evt);
            }
        });

        jazzButon.setText("Jazz Sarkilar");
        jazzButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jazzButonActionPerformed(evt);
            }
        });

        klasikButon.setText("Klasik Sarkilar");
        klasikButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klasikButonActionPerformed(evt);
            }
        });

        aramaKutucuk.setText("Arama Kutucugu :");

        kullaniciAdiLabel.setText("Kullanici adi gelecek");

        jButton2.setText("Top 10");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pop Listem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Jazz Listem");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Klasik Listem");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Sarki Listem");

        jButton7.setText("Sarki Ekle(ID)");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton8.setText("Takip Et");
        jButton8.setVisible(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setText("Pop ");
        jButton11.setVisible(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setText("Klasik");
        jButton13.setVisible(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton14.setText("Jazz");
        jButton14.setVisible(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton12.setText("BUL(k.adi)");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Kisi Bulundu");
        jLabel2.setVisible(false);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Kisi Bulunamadi");
        jLabel3.setVisible(false);

        jButton15.setText("Tümünü Ekle");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jButton15.setVisible(false);

        jButton17.setText("Tümünü Ekle");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jButton17.setVisible(false);

        jButton19.setText("Tümünü Ekle");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jButton19.setVisible(false);

        jButton20.setText("Ulke Top 10");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton21.setText("Dinle(Sarki ID)");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Dinlendi");
        jLabel5.setVisible(false);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Bulunamadi");
        jLabel6.setVisible(false);

        jButton22.setText("Sarki Ara(Adi)");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Ödedim");
        jButton23.setVisible(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Ödemedim");
        jButton24.setVisible(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "K.Adi"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Bulunamadi");
        jLabel8.setVisible(false);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sarki ID", "Sarki Adi", "Tarih", "Sanatci Adi", "Album", "Tur", "Sure", "Din.Sayi."
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(1);
        }

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Eklenemedi");
        jLabel9.setVisible(false);

        jLabel10.setForeground(new java.awt.Color(0, 255, 0));
        jLabel10.setText("Eklendi");
        jLabel10.setVisible(false);

        jLabel11.setForeground(new java.awt.Color(0, 255, 0));
        jLabel11.setText("Basarili");
        jLabel11.setVisible(false);

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Basarisiz");
        jLabel12.setVisible(false);

        jLabel13.setForeground(new java.awt.Color(102, 255, 255));
        jLabel13.setText("PREMIUM");
        jLabel13.setVisible(false);

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Kisi Premium Degil");
        jLabel7.setVisible(false);

        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setText("Basarili");
        jLabel14.setVisible(false);

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Basarisiz");
        jLabel15.setVisible(false);

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Zaten Var");
        jLabel16.setVisible(false);

        jLabel17.setForeground(new java.awt.Color(0, 255, 0));
        jLabel17.setText("Eklendi");
        jLabel17.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton19)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton15)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(aramaKutucuk, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aramaKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(klasikButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jazzButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(popButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel10)))
                                .addGap(28, 28, 28)
                                .addComponent(popButon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jazzButon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(klasikButon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aramaKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aramaKutucuk)
                                    .addComponent(jButton22)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton12)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton17)
                                        .addComponent(jButton15)
                                        .addComponent(jButton19))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton23)
                            .addComponent(jButton24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(65, 65, 65)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(96, 96, 96)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aramaKutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaKutusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aramaKutusuActionPerformed

    private void popButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popButonActionPerformed
        tabloyuTemizle();
        tumTurSarkilariGoruntule("pop");
    }//GEN-LAST:event_popButonActionPerformed

    private void klasikButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klasikButonActionPerformed
        tabloyuTemizle();
        tumTurSarkilariGoruntule("klasik");
    }//GEN-LAST:event_klasikButonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tabloyuTemizle();
        sarkiListeTop10Olusturma();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        mesajlariKapat();
        kullanicininPlaylistininTumunuEkle("Pop");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        mesajlariKapat();
        kullanicininPlaylistininTumunuEkle("Jazz");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        mesajlariKapat();
        kullanicininPlaylistininTumunuEkle("Klasik");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        tabloyuTemizle();
        sarkiListeUlkeTop10Olusturma();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        mesajlariKapat();
        tuslariKapat();        
        arama();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        mesajlariKapat();
        sarkiDinle();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        tabloyuTemizle();
        mesajlariKapat();
        sarkiAra();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jazzButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jazzButonActionPerformed
        tabloyuTemizle();
        tumTurSarkilariGoruntule("jazz");
    }//GEN-LAST:event_jazzButonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mesajlariKapat();
        kullaniciSarkiEkle(kullaniciAdi,Integer.parseInt(jTextField4.getText()));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       tabloyuTemizle();
       kullaniciSarkilariListele("klasik");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
         mesajlariKapat();
         odedimMi("1");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        mesajlariKapat();
        odedimMi("0");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tabloyuTemizle();
        kullaniciSarkilariListele("pop");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       tabloyuTemizle();
       kullaniciSarkilariListele("jazz");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        tabloyuTemizle();
        kullanicininPlaylistiniGoruntule("Pop");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        tabloyuTemizle();
        kullanicininPlaylistiniGoruntule("Jazz");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        tabloyuTemizle();
        kullanicininPlaylistiniGoruntule("Klasik");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       mesajlariKapat();
       kullaniciTakipEt();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       kucukTabloyuTemizle();
       takipEdilenleriGoruntule();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void odedimMi(String hangi) {
        try {
            Connection();
            String query = "UPDATE kullanicilar SET  odendi = "+hangi+" WHERE kullaniciAdi= '" + kullaniciAdi + "'";
            PreparedStatement pst = con.prepareStatement(query);
            pst.execute();
            jLabel11.setVisible(true);
        } catch (Exception e) {
            jLabel12.setVisible(true);
            System.out.println(e.getMessage());
        }
    }
    public void kullaniciSarkiEkle(String kullaniciAdi,int eklenecekID) {
        try {
            Connection();
            String query = new String();
            String query2 = new String();
            String nereye = "Select tur From sarkilar WHERE sarkiID= " + eklenecekID;

            PreparedStatement pstNereye = con.prepareStatement(nereye);
            //pstNereye.setInt(1, ;
            ResultSet rsNereye = pstNereye.executeQuery();
            if (rsNereye.next()) {
                String tur = rsNereye.getString("tur");
                if (tur.equals("Pop")) {
                    query = " insert into " + kullaniciAdi + "pop (sarkiID)"
                            + " values (?)";
                    query2 = "Select * From " + kullaniciAdi + "pop WHERE sarkiID=?";
                } else if (tur.equals("Jazz")) {
                    query = " insert into " + kullaniciAdi + "jazz (sarkiID)"
                            + " values (?)";
                    query2 = "Select * From " + kullaniciAdi + "jazz WHERE sarkiID=?";
                } else if (tur.equals("Klasik")) {
                    query = " insert into " + kullaniciAdi + "klasik (sarkiID)"
                            + " values (?)";
                    query2 = "Select * From " + kullaniciAdi + "klasik WHERE sarkiID=?";
                }
                PreparedStatement pst = con.prepareStatement(query);
                PreparedStatement pst2 = con.prepareStatement(query2);
                pst2.setInt(1, eklenecekID);
                pst.setInt(1, eklenecekID);
                ResultSet rs1 = pst2.executeQuery();
                if (rs1.next()) {
                    jLabel9.setVisible(true);
                    jTextField4.setText("");
                } else {
                    jLabel10.setVisible(true);
                    jTextField4.setText("");
                    pst.execute();
                }
            } else {
                jLabel9.setVisible(true);
            }

            //con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void takipEdilenleriGoruntule(){
        try {
            Connection();
            String query = "Select * from "+kullaniciAdi+"takipedilenler";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String ID = String.valueOf(rs1.getInt("ID"));
                String kullaniciAdi = rs1.getString("kullaniciAdi");
                String tabloVeri[] = {ID, kullaniciAdi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void kullaniciTakipEt() {
        try {
            Connection();
            
            String query3 = "Select ID from kullanicilar WHERE kullaniciAdi= '"+arananKullaniciAdi+"'";
            
            PreparedStatement pst3 = con.prepareStatement(query3);
            ResultSet rs3 = pst3.executeQuery();
            rs3.next();
            int degisken = rs3.getInt("ID");
            String query2 = "Select * from "+kullaniciAdi+"takipedilenler WHERE ID= "+degisken;
            PreparedStatement pst2 = con.prepareStatement(query2);
            ResultSet rs2 = pst2.executeQuery();
            if(rs2.next()){
                jLabel16.setVisible(true);
            }
            else{
                String query = "INSERT INTO "+kullaniciAdi+"takipedilenler (ID,kullaniciAdi) VALUES ("+degisken+",'"+arananKullaniciAdi+"')";
                PreparedStatement pst = con.prepareStatement(query);
                jLabel17.setVisible(true);
                pst.execute();
            }
            con.close();
        } catch (Exception e) {
            jLabel16.setVisible(true);
            System.out.println(e.getMessage());
        }
    }
    public void tumTurSarkilariGoruntule(String turs) {
        try {
            Connection();
            String query = "SELECT * From sarkilar WHERE tur = '" + turs + "'";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String sarkiAdi = rs1.getString("sarkiAdi");
                String tarih = rs1.getString("tarih");
                String sanatciAdi = rs1.getString("sanatciAdi");
                String album = rs1.getString("album");
                String tur = rs1.getString("tur");
                String sure = rs1.getString("sure");
                String dinlenmeSayisi = String.valueOf(rs1.getInt("dinlenmeSayisi"));
                String tabloVeri[] = {sarkiID, sarkiAdi, tarih, sanatciAdi, album, tur, sure, dinlenmeSayisi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void tabloyuTemizle() {
        DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
        tblModel.setRowCount(0);
    }
    public void kucukTabloyuTemizle() {
        DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();
        tblModel.setRowCount(0);
    }

    public void sarkiDinle() {
        try {
            Connection();
            String query = "UPDATE sarkilar SET dinlenmeSayisi = ? WHERE sarkiID = ?";
            String query2 = "SELECT * FROM sarkilar WHERE sarkiID = ?";
            PreparedStatement pst2 = con.prepareStatement(query2);
            pst2.setString(1, jTextField6.getText());
            ResultSet rs1 = pst2.executeQuery();
            if (rs1.next()) {
                jLabel5.setVisible(true);
                yeniDeger = String.valueOf(rs1.getInt("dinlenmeSayisi") + 1);
            } else {
                jLabel6.setVisible(true);
            }
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, yeniDeger);
            pst.setString(2, jTextField6.getText());
            pst.execute();
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void kullanicininPlaylistininTumunuEkle(String Turs) {
        try {
            Connection();
            String query = "SELECT * From "+arananKullaniciAdi+Turs;
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String query2 = "SELECT * From sarkilar WHERE sarkiID= "+sarkiID;
                PreparedStatement pst2 = con.prepareStatement(query2);
                ResultSet rs2 = pst2.executeQuery();
                rs2.next();
                //String sarkiID2 = String.valueOf(rs2.getInt("sarkiID"));
                kullaniciSarkiEkle(kullaniciAdi,rs2.getInt("sarkiID"));
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void kullanicininPlaylistiniGoruntule(String Turs) {
        try {
            Connection();
            String query = "SELECT * From "+arananKullaniciAdi+Turs;
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String query2 = "SELECT * From sarkilar WHERE sarkiID= "+sarkiID;
                PreparedStatement pst2 = con.prepareStatement(query2);
                ResultSet rs2 = pst2.executeQuery();
                rs2.next();
                String sarkiID2 = String.valueOf(rs2.getInt("sarkiID"));
                String sarkiAdi = rs2.getString("sarkiAdi");
                String tarih = rs2.getString("tarih");
                String sanatciAdi = rs2.getString("sanatciAdi");
                String album = rs2.getString("album");
                String tur = rs2.getString("tur");
                String sure = rs2.getString("sure");
                String dinlenmeSayisi = String.valueOf(rs2.getInt("dinlenmeSayisi"));
                String tabloVeri[] = {sarkiID2, sarkiAdi, tarih, sanatciAdi, album, tur, sure, dinlenmeSayisi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void kullanicidanSarkiEkle(String eklenecekOlanID) {
            try {
            Connection();
            String query = new String();
            String query2 = new String();
            String nereye = "Select tur From sarkilar WHERE sarkiID= " + eklenecekOlanID;

            PreparedStatement pstNereye = con.prepareStatement(nereye);
            //pstNereye.setInt(1, ;
            ResultSet rsNereye = pstNereye.executeQuery();
            if (rsNereye.next()) {
                String tur = rsNereye.getString("tur");
                System.out.println(tur);
                if (tur.equals("Pop")) {
                    query = " insert into " + kullaniciAdi + "pop (sarkiID)"
                            + " values (?)";
                    query2 = "Select * From " + kullaniciAdi + "pop WHERE sarkiID=?";
                } else if (tur.equals("Jazz")) {
                    query = " insert into " + kullaniciAdi + "jazz (sarkiID)"
                            + " values (?)";
                    query2 = "Select * From " + kullaniciAdi + "jazz WHERE sarkiID=?";
                } else if (tur.equals("Klasik")) {
                    query = " insert into " + kullaniciAdi + "klasik (sarkiID)"
                            + " values (?)";
                    query2 = "Select * From " + kullaniciAdi + "klasik WHERE sarkiID=?";
                }
                PreparedStatement pst = con.prepareStatement(query);
                PreparedStatement pst2 = con.prepareStatement(query2);
                pst2.setInt(1, Integer.parseInt(eklenecekOlanID));
                pst.setInt(1, Integer.parseInt(eklenecekOlanID));
                ResultSet rs1 = pst2.executeQuery();
                if (rs1.next()) {
                    jLabel9.setVisible(true);
                    jTextField4.setText("");
                } else {
                    jLabel10.setVisible(true);
                    jTextField4.setText("");
                    pst.execute();
                }
            } else {
                jLabel9.setVisible(true);
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void sarkiAra() {
        try {
            Connection();
            String query = "SELECT * FROM sarkilar WHERE sarkiAdi LIKE ?;";
            PreparedStatement pst = con.prepareStatement(query);
            String aranacakSey = "%" + aramaKutusu.getText() + "%";
            pst.setString(1, aranacakSey);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String sarkiAdi = rs1.getString("sarkiAdi");
                String tarih = rs1.getString("tarih");
                String sanatciAdi = rs1.getString("sanatciAdi");
                String album = rs1.getString("album");
                String tur = rs1.getString("tur");
                String sure = rs1.getString("sure");
                String dinlenmeSayisi = String.valueOf(rs1.getInt("dinlenmeSayisi"));
                String tabloVeri[] = {sarkiID, sarkiAdi, tarih, sanatciAdi, album, tur, sure, dinlenmeSayisi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    //1234
    public void sarkiListeUlkeTop10Olusturma() {
        try {
            Connection();
            String query = "SELECT * From sarkilar WHERE sanatciAdi = 'ekmekogluekmeginoglu'";
            String query2 = "SELECT * From sanatcilar WHERE ulkesi = '"+jTextField3.getText()+"'";
            PreparedStatement pst2 = con.prepareStatement(query2);
            ResultSet rs2 = pst2.executeQuery();
            while(rs2.next()){
                query += "OR sanatciAdi = '"+rs2.getString("sanatciAdi")+"' ";
            }
            
            query += " ORDER BY dinlenmeSayisi DESC LIMIT 10";
            //jTextField3
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String sarkiAdi = rs1.getString("sarkiAdi");
                String tarih = rs1.getString("tarih");
                String sanatciAdi = rs1.getString("sanatciAdi");
                String album = rs1.getString("album");
                String tur = rs1.getString("tur");
                String sure = rs1.getString("sure");
                String dinlenmeSayisi = String.valueOf(rs1.getInt("dinlenmeSayisi"));
                String tabloVeri[] = {sarkiID, sarkiAdi, tarih, sanatciAdi, album, tur, sure, dinlenmeSayisi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void sarkiListeTop10Olusturma() {
        try {
            Connection();
            String query = "SELECT * From sarkilar ORDER BY dinlenmeSayisi DESC LIMIT 10";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String sarkiAdi = rs1.getString("sarkiAdi");
                String tarih = rs1.getString("tarih");
                String sanatciAdi = rs1.getString("sanatciAdi");
                String album = rs1.getString("album");
                String tur = rs1.getString("tur");
                String sure = rs1.getString("sure");
                String dinlenmeSayisi = String.valueOf(rs1.getInt("dinlenmeSayisi"));
                String tabloVeri[] = {sarkiID, sarkiAdi, tarih, sanatciAdi, album, tur, sure, dinlenmeSayisi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void kullaniciSarkilariListele(String Turs){
        //kullaniciAdi
        try {
            Connection();
            String query = "SELECT * From "+kullaniciAdi+Turs;
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                String sarkiID = String.valueOf(rs1.getInt("sarkiID"));
                String query2 = "SELECT * From sarkilar WHERE sarkiID= "+sarkiID;
                PreparedStatement pst2 = con.prepareStatement(query2);
                ResultSet rs2 = pst2.executeQuery();
                rs2.next();
                String sarkiID2 = String.valueOf(rs2.getInt("sarkiID"));
                String sarkiAdi = rs2.getString("sarkiAdi");
                String tarih = rs2.getString("tarih");
                String sanatciAdi = rs2.getString("sanatciAdi");
                String album = rs2.getString("album");
                String tur = rs2.getString("tur");
                String sure = rs2.getString("sure");
                String dinlenmeSayisi = String.valueOf(rs2.getInt("dinlenmeSayisi"));
                String tabloVeri[] = {sarkiID2, sarkiAdi, tarih, sanatciAdi, album, tur, sure, dinlenmeSayisi};
                DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(tabloVeri);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void arama(){
        try {
            Connection();
            String query = "SELECT * FROM kullanicilar WHERE kullaniciAdi= '"+jTextField5.getText()+"'";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs1 = pst.executeQuery();
            if (rs1.next()) {
                if(rs1.getBoolean("premium")== true && rs1.getBoolean("odendi")== true  ) {
                arananKullaniciAdi=rs1.getString("kullaniciAdi");
                jButton11.setVisible(true);
                jButton19.setVisible(true);
                jButton14.setVisible(true);
                jButton15.setVisible(true);
                jButton13.setVisible(true);
                jButton17.setVisible(true);
                jButton8.setVisible(true);
                jLabel2.setVisible(true);
                }
                else
                    jLabel7.setVisible(true);
            }
            else
                jLabel3.setVisible(true);
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void tuslariKapat(){
        jButton11.setVisible(false);
        jButton19.setVisible(false);
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        jButton13.setVisible(false);
        jButton17.setVisible(false);
        jButton8.setVisible(false);
        jLabel2.setVisible(false);
    }
    public void mesajlariKapat() {
        jLabel8.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
    }
    public void Connection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            this.con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/spotify", "root", "password");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    //kapadın unutmma
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KPencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KPencere("ykullanici1").setVisible(true);
//            }
//        });
//    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aramaKutucuk;
    private javax.swing.JTextField aramaKutusu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jazzButon;
    private javax.swing.JButton klasikButon;
    private javax.swing.JLabel kullaniciAdiLabel;
    private javax.swing.JButton popButon;
    // End of variables declaration//GEN-END:variables
}
